openapi: 3.0.1
info:
  version: 1.1.0
  title: GMAF
  description: GMAF REST
  contact:
    name: Stefan Wagenpfeil, Patrick Steinert
servers:
  - url: http://85.215.58.111:8242/gmaf/gmafApi
paths:
  /gmaf/getToken/{api-key}:
    get:
      operationId: getAuthToken
      parameters:
        - name: api-key
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                type: string
  /gmaf/getCollection/{auth-token}:
    post:
      operationId: getCollection
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MMFG'
  /gmaf/get-collection-ids/{auth-token}:
    post:
      operationId: getCollectionIds
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /gmaf/getMetadata/{auth-token}:
    post:
      operationId: getCollectionMetadata
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeneralMetadata'
  /gmaf/preview/{auth-token}/{id}:
    get:
      operationId: getImage
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            image/*: {}
    post:
      operationId: getPreviewURL
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /gmaf/getmmfg/{auth-token}/{mmfg-id}:
    post:
      operationId: getMMFGForId
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
        - name: mmfg-id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MMFG'
  /gmaf/getgc/{auth-token}/{mmfg_id}:
    post:
      operationId: getOrGenerateGraphCode
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
        - name: mmfg_id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /gmaf/getRec/{auth-token}/{id}:
    post:
      operationId: getRecommendedAssets
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MMFG'
  /gmaf/{session}/{api-key}:
    post:
      operationId: getSession
      parameters:
        - name: session
          in: path
          required: true
          schema:
            type: string
        - name: api-key
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GMAF'
  /gmaf/getsimilarassetsbygraphcode/{auth-token}:
    post:
      operationId: getSimilarAssetIDsByGraphCode
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /gmaf/getSim/{auth-token}/{id}:
    post:
      operationId: getSimilarAssets
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MMFG'
  /gmaf/query/{auth-token}/{query}:
    post:
      operationId: queryByKeyword
      parameters:
        - name: auth-token
          in: path
          required: true
          schema:
            type: string
        - name: query
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api:
    get:
      operationId: setProcessingPlugins
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /api/getAuthToken:
    get:
      operationId: getAuthToken_1
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/xml: {}
  /application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          description: default response
          content:
            application/vnd.sun.wadl+xml: {}
            application/xml: {}
components:
  schemas:
    AssetLink:
      type: object
      properties:
        type:
          type: integer
          format: int32
        location:
          type: string
          format: url
        assetName:
          type: string
    CompositionRelationship:
      type: object
      properties:
        type:
          type: integer
          format: int32
        relatedObject:
          $ref: '#/components/schemas/Node'
    Context:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
          format: uuid
    GeneralMetadata:
      type: object
      properties:
        id:
          type: string
          format: uuid
        longitude:
          type: integer
          format: int64
        latitude:
          type: integer
          format: int64
        cameraModel:
          type: string
        lensModel:
          type: string
        aperture:
          type: number
          format: float
        exposure:
          type: number
          format: float
        cityNearBy:
          type: string
        focalLength:
          type: integer
          format: int64
        resolution:
          type: integer
          format: int32
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        date:
          type: string
          format: date-time
        fileSize:
          type: integer
          format: int64
        iso:
          type: integer
          format: int32
        shutterSpeed:
          type: integer
          format: int64
        fileName:
          type: string
        fileReference:
          type: string
          format: binary
        previewUrl:
          type: string
          format: url
        sourceSystem:
          type: string
          format: uuid
    Location:
      type: object
      properties:
        type:
          type: integer
          format: int32
        location:
          type: string
          format: url
        name:
          type: string
    MMFG:
      type: object
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        generalMetadata:
          $ref: '#/components/schemas/GeneralMetadata'
        security:
          $ref: '#/components/schemas/Security'
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Location'
        currentNode:
          $ref: '#/components/schemas/Node'
        similarity:
          type: array
          items:
            type: number
            format: float
        tempSimilarity:
          type: array
          items:
            type: number
            format: float
        allNodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        collectionElements:
          type: array
          items:
            $ref: '#/components/schemas/MMFG'
        id:
          type: string
          format: uuid
        begin:
          $ref: '#/components/schemas/Timerange'
        end:
          $ref: '#/components/schemas/Timerange'
    Node:
      type: object
      properties:
        name:
          type: string
        weights:
          type: array
          items:
            $ref: '#/components/schemas/Weight'
        technicalAttributes:
          type: array
          items:
            $ref: '#/components/schemas/TechnicalAttribute'
        semanticRelationships:
          type: array
          items:
            $ref: '#/components/schemas/SemanticRelationship'
        compositionRelationships:
          type: array
          items:
            $ref: '#/components/schemas/CompositionRelationship'
        assetLinks:
          type: array
          items:
            $ref: '#/components/schemas/AssetLink'
        detectedBy:
          type: string
        timerange:
          $ref: '#/components/schemas/Timerange'
        featureVector:
          $ref: '#/components/schemas/MMFG'
    Security:
      type: object
      properties:
        owner_id:
          type: string
        group_id:
          type: string
        acl:
          type: string
    SemanticRelationship:
      type: object
      properties:
        relatedNode:
          type: string
          format: url
        description:
          type: string
    TechnicalAttribute:
      type: object
      properties:
        relative_x:
          type: integer
          format: int32
        relative_y:
          type: integer
          format: int32
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        sharpness:
          type: number
          format: float
        blurryness:
          type: number
          format: float
        dominantColors:
          type: array
          items:
            type: object
            properties:
              red:
                type: integer
                format: int32
              green:
                type: integer
                format: int32
              blue:
                type: integer
                format: int32
              alpha:
                type: integer
                format: int32
              colorSpace:
                type: object
                properties:
                  type:
                    type: integer
                    format: int32
                  numComponents:
                    type: integer
                    format: int32
                  cs_sRGB:
                    type: boolean
              rgb:
                type: integer
                format: int32
              transparency:
                type: integer
                format: int32
    Timerange:
      type: object
      properties:
        begin:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        universalTime:
          type: boolean
        relativeTime:
          type: boolean
    Weight:
      type: object
      properties:
        context:
          $ref: '#/components/schemas/Context'
        weight:
          type: number
          format: float
    GMAF:
      type: object
      properties:
        processingPlugins:
          type: array
          writeOnly: true
          items:
            type: string
        plugins:
          type: array
          items:
            type: string
    GraphCode:
      type: object
      properties:
        dictionary:
          type: array
          items:
            type: string
        collectionElements:
          type: array
          items:
            $ref: '#/components/schemas/GraphCode'
        relationships:
          type: array
          items:
            type: array
            items:
              type: integer
              format: int32
        collection:
          type: boolean
