/*
 * GMAF
 * GMAF REST
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tei.mmir.gmaf.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.tei.mmir.gmaf.model.TechnicalAttributeDominantColorsInnerColorSpace;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TechnicalAttributeDominantColorsInner
 */
public class TechnicalAttributeDominantColorsInnerTest {
    private final TechnicalAttributeDominantColorsInner model = new TechnicalAttributeDominantColorsInner();

    /**
     * Model tests for TechnicalAttributeDominantColorsInner
     */
    @Test
    public void testTechnicalAttributeDominantColorsInner() {
        // TODO: test TechnicalAttributeDominantColorsInner
    }

    /**
     * Test the property 'red'
     */
    @Test
    public void redTest() {
        // TODO: test red
    }

    /**
     * Test the property 'green'
     */
    @Test
    public void greenTest() {
        // TODO: test green
    }

    /**
     * Test the property 'blue'
     */
    @Test
    public void blueTest() {
        // TODO: test blue
    }

    /**
     * Test the property 'alpha'
     */
    @Test
    public void alphaTest() {
        // TODO: test alpha
    }

    /**
     * Test the property 'colorSpace'
     */
    @Test
    public void colorSpaceTest() {
        // TODO: test colorSpace
    }

    /**
     * Test the property 'rgb'
     */
    @Test
    public void rgbTest() {
        // TODO: test rgb
    }

    /**
     * Test the property 'transparency'
     */
    @Test
    public void transparencyTest() {
        // TODO: test transparency
    }

}
