/*
 * GMAF
 * GMAF REST
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tei.mmir.gmaf.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Timerange
 */
public class TimerangeTest {
    private final Timerange model = new Timerange();

    /**
     * Model tests for Timerange
     */
    @Test
    public void testTimerange() {
        // TODO: test Timerange
    }

    /**
     * Test the property 'begin'
     */
    @Test
    public void beginTest() {
        // TODO: test begin
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'universalTime'
     */
    @Test
    public void universalTimeTest() {
        // TODO: test universalTime
    }

    /**
     * Test the property 'relativeTime'
     */
    @Test
    public void relativeTimeTest() {
        // TODO: test relativeTime
    }

}
